### PR TITLE
Added project linting and formating setup via only prettier and eslint

### LINKED ISSUE #3: Add project linting, pre-commit actions

### PR DESCRIPTION
**Pull request by Ryan-Zayne**
Resolves #3

### CODE REVIEW

**Comment by Ryan-Zayne** [comment]
If there seems to be any open source contribution guideline I've failed to comply with, please pray tell

**Comment by babblebey** [comment]
Great stuff @Ryan-Zayne 

You have done well for a start. 🤲🏾

**Comment by Ryan-Zayne** [comment]
> Great stuff @Ryan-Zayne
> 
> You have done well for a start. 🤲🏾

I appreciate

**Review by 289Volts — APPROVED** [review]
Well done @Ryan-Zayne 

Thank you for your contribution

**Comment by Klin-Coders** [comment]
@Ryan-Zayne kindly resolve merge conflict

**Comment by Klin-Coders** [comment]
could we also integrate husky and pre. commit hooks?

**Review by Klin-Coders — COMMENTED** [review]
Conflicts needs resolution

**Comment by Ryan-Zayne** [comment]
> Conflicts needs resolution

I'll look into it

**Comment by Ryan-Zayne** [comment]
Fixed Merge Conflicts @Klin-Coders

**Pull request merged**
